# Site settings
title: The Napping Man
email: sncollie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ARGH!!!!!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "sncollie.github.io" # the base hostname & protocol for your site
twitter_username: TheNappingMan
github_username:  sncollie
highlighter: rouge

# Build settings
markdown: kramdown
